name: OSV-Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  osv-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Clean Go environment and install dependencies
        run: |
          go clean -cache -modcache -i -r
          go mod download
          go mod tidy

      - name: Build the project
        run: |
          go build ./...
          go test ./...

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Download OSV-Scanner
        run: |
          wget https://github.com/google/osv-scanner/releases/download/v1.8.1/osv-scanner_linux_amd64 -O osv-scanner
          chmod +x osv-scanner

      #- name: Run OSV-Scanner
      #  run: ./osv-scanner --recursive .

      - name: Run govulncheck
        run: govulncheck ./...
