name: OSV-Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  osv-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Download OSV-Scanner
        run: |
          wget https://github.com/google/osv-scanner/releases/download/v1.8.1/osv-scanner_linux_amd64 -O osv-scanner
          chmod +x osv-scanner
          ./osv-scanner --recursive .
